# -*- coding: utf-8 -*-
"""Calculater.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tlqEM-mo39LoGZBqpB1gTHFnjSECr8-r
"""

def main():
  print("Enter one of these options:\n"+"1-Addition \n"+"2-Subtraction \n"+"3-Multiply")
  options()

def options():
  o=int(input("Option: "))
  if o ==1:
    o=int(input("enter the 1st Number:"))
    t=int(input("enter the 2nd Number:"))
    add(a1=o,a2=t)
  elif o ==2:
    o=int(input("enter the 1st Number:"))
    t=int(input("enter the 2nd Number:"))
    sub(s1=o,s2=t)
  elif o ==3:
    o=int(input("enter the 1st Number:"))
    t=int(input("enter the 2nd Number:"))
    mult(m1=o,m2=t)
  

def add(a1,a2):
  ra=(a1+a2)
  print(a1," + ", a2," = ",ra)
  


def sub(s1,s2):
  
  rs=(s1-s2)
  print(s1," - ", s2," = ",rs)
    

def mult(m1,m2):

  rm=m1*m2
  print(m1," X ", m2," = ",rm)
    
main()