# -*- coding: utf-8 -*-
"""PythonBank.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xxq6NpGmWwmanPs28YisCtrlGV11MdjS
"""

print("Welcome")
password=1234
balance=1200
option=0
start=input("Please Print Y to start: ")
while start=="y" or start=="Y":
  
  x=(input("Enter Password: "))
  if (x==password):
    option=int(input("Input 1 to Withdraw Money \n""Input 2 to Deposit Money \n""Input 3 show balance \n""Input 4 change password: \n" ))
    if(option==1):
      withdraw=int(input("Enter Withdraw Amount: $"))
      balance= balance - withdraw
      print("you have Withdrawn $",withdraw,"\nyour Balance is now: $",balance)
    elif(option==2):
      deposit=int(input("Enter Deposit Amount "))
      balance=balance+deposit
      print("you have Deposited $",deposit, "\nyour Balance is now: $",balance)
    elif(option==3):
      print(balance)
    elif(option==4):
      password=input("enter old password: ")
      if (password==password):
        password=input("enter your NEw password: ")

    start=input("Do you have another transaction please print Y for Yes: ")

  else:
    print("Password entered is wrong. Please enter your password: ")