# -*- coding: utf-8 -*-
"""StudentDictionary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18IapzoXwTBAecfWuskVHfguHtu31zp4X
"""

##Write a program which contains dictionary and keeps the student names and id numbers as key value pair.
##The program should display a menu that lets the user look up a student's id number, add a new name and id number, and delete an existing name and id number.

d={'Moe':1234, 'John':2222, "Martin": 3232}
while True:
  print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>")
  print("1.Show all Student & ID \n2.search Student for ID \n3.add Student and ID\n4.delete Student and ID")
  ans=int (input("Please enter one of the option: "))

  if ans==1:
    for name, id in d.items():
     print("Name:",name, ' ', "ID:",id)
    
  elif ans==2:
    a=input("Enter Name for ID? ")
    print(a, ":",d[a])
 
  elif ans==3:
    n1=input("Enter Name & ID separated by  ':' ")
    n2=n1.split(":")
    d[n2[0]]=int(n2[1])
    print("ADDED TO THE DATABASE!")
    for name, id in d.items():
      print("Name:",name, ' ', "ID:",id)
    break
  elif ans==4:
    dlt=input("Enter Name to delete: ")
    d.pop(dlt)
    for name, id in d.items():
      print("Name:",name, ' ', "ID:",id)
    break
  else:
    print("please try again")