# -*- coding: utf-8 -*-
"""Vending_Machine.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JIIrVk-vLDFXQUq6YlojoiuCJnRx4sAf
"""

def main():
  print("Enter one of these options:\n"+"->Snack \n"+"->Drinks")
  options()
def options():
  #picking if you want a drink or a snack
  o=(input("Option: "))
  if o in ['snacks', 'snack', 'Snack', 'Snacks']:
    snacks()
  elif o in ["Drinks","drinks","Drink","drink"]:
    drinks()
  else:
    print("sorry incorrect input")
    main()
def snacks():
  snack=["0-Doritos", "1-Oreo", "2-Lay's", "3-KitKat","4-Fritos"]
  snack_price=[2,1,2,1.5,2]
  print("please choose once of the options\n")
#you snack options 
  for s in snack:
    print("Option",s)

#picking your snack and seeing its price 
  cs=int(input("Enter Choice:"))
  if cs==0:
    print("You have choosen",snack[0],"Price:",snack_price[0])
    amount=snack_price[cs]

  elif cs==1:
    print("You have choosen",snack[1],"Price:",snack_price[1])
    amount=snack_price[cs]

  elif cs==2:
    print("You have choosen",snack[2],"Price:",snack_price[2])
    amount=snack_price[cs]

  elif cs==3:
    print("You have choosen",snack[3],"Price:",snack_price[3])
    amount=snack_price[cs]

  elif cs==4:
    print("You have choosen",snack[4],"Price:",snack_price[4])
    amount=snack_price[cs]
  else:
    print("incorrect input please try aagian")
    snacks()
#calculating total and refund or returning change
  mny=int(input("please insert amount...\n"))
  if mny>amount:
    total=mny-amount
    print("change:", total,"\n have a great day")
  elif mny<amount:
    total=mny-amount
    print("please insert ",total," to complete transaction\n or enter 0 to cancel the transaction")
    answer=input("enter amount here")
    if answer==0:
      print("thanks you have a great day\n refund:", mny)
    elif answer > total:
      ifTotal=answer-total
      print("thank you, have a great day\n change:", iftotal)
  else:
    print("have a greatday")

  
def drinks():
#your drink options 
  drink=["0-Coke","1-Sprite","2-Juice","3-Water","4-7Up"]
  drink_price=[2,2,1,1,2]
  print(" please choose once of the options\n")
  for d in drink:
    print(d)
#your drink choice and price  
  cd=int(input("Enter Choice:"))
  if cd==0:
    print("You have choosen",drink[0],"Price:",drink_price[0])
    amount=drink_price[cd]
  elif cd==1:
    print("You have choosen",drink[1],"Price:",drink_price[1])
    amount=drink_price[cd]

  elif cd==2:
    print("You have choosen",drink[2],"Price:",drink_price[2])
    amount=drink_price[cd]
  
  elif cd==3:
    print("You have choosen",drink[3],"Price:",drink_price[3])
    amount=drink_price[cd]

  elif cd==4:
    print("You have choosen",drink[4],"Price:",drink_price[4])
    amount=drink_price[cd]

#calculate total amount fo drinks
  mny=int(input("please insert amount...\n"))
  if mny>amount:
    total=mny-amount
    print("change:", total,"\nHave a great day")
  elif mny<amount:
    total=mny-amount
    print("please insert ",total," to complete transaction\nOr enter 0 to cancel the transaction")
    answer=input("enter amount here")
    if answer==0:
      print("thanks you have a great day\nRefund:", mny)
    elif answer > total:
      ifTotal=answer-total
      print("thank you, have a great day\nChange:", iftotal)
  else:
    print("have a greatday")








main()